name: noise_meter
description: A Flutter plugin for collecting noise from the phone's microphone.
version: 5.1.1
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/noise_meter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_streamer:
    path: ../audio_streamer

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  pubspec_parse: any
  flutter_lints: any
